version: 2

models:
  - name: stg_orders
    description: Cleaned and standardized order-level data from the raw Superstore CSV.
    columns:
      - name: order_id
        description: Unique identifier for the order.
        data_tests:
          - not_null

      - name: order_date
        description: Date the order was placed.
        data_tests: [not_null]

      - name: ship_date
        description: Date the order was shipped.
        data_tests: [not_null]

      - name: segment
        description: Customer segment category.
        data_tests:
          - not_null
          - accepted_values:
              values: ['Consumer', 'Corporate', 'Home Office']

      - name: region
        description: Geographic region of the customer.
        data_tests:
          - not_null
          - accepted_values:
              values: ['East', 'West', 'Central', 'South']

      - name: sales
        description: Sales amount for the order.
        data_tests: [not_null]

      - name: quantity
        description: Quantity of items ordered.
        data_tests:
          - not_null

      - name: discount
        description: Discount applied on the order.
        data_tests:
          - not_null

      - name: profit
        description: Profit generated from the order.
        data_tests: [not_null]

  - name: fct_daily_sales
    description: Final fact model with daily sales totals and profit margin.
    columns:
      - name: order_date
        description: Date of aggregated sales.
        data_tests:
          - not_null
          - unique

      - name: total_sales
        description: Total sales for the day.
        data_tests: [not_null]

      - name: total_quantity
        description: Total quantity sold on that day.
        data_tests: [not_null]

      - name: total_profit
        description: Total profit on that day.
        data_tests: [not_null]

      - name: profit_margin_percent
        description: Profit margin as a percentage of sales.
        data_tests:
          - not_null
